name: videocrash
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  video_player: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter